name: CubitPy test suite

on:
  schedule:
    - cron: '0 04 * * *'
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

env:
  CUBIT_DOWNLOAD_URL: https://f002.backblazeb2.com/file/cubit-downloads/Coreform-Cubit/Releases/Linux/Coreform-Cubit-2025.8%2B61943-Lin64.tar.gz

jobs:
  testing_coreform:
    name: CubitPy tests with Coreform (can access cubit secrets)
    runs-on: ubuntu-latest
    environment:
      # Use the trusted environment only for PRs authored by an COLLABORATOR (no approval needed); all others use the untrusted environment (someone has to approve the workflow run).
      # Otherwise (scheduled or merge triggers) use the trusted environment (no approval needed).
      name: ${{ github.event_name == 'pull_request_target' && (github.event.pull_request.author_association == 'COLLABORATOR') && 'cubit_secrets_trusted' || (github.event_name == 'pull_request_target' && 'cubit_secrets_untrusted' || 'cubit_secrets_trusted') }}
    env:
      PYTHON_VENV: python-testing-environment
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v7
        with:
          submodules: true
          # For PR runs, checkout PR code; otherwise fallback to default branch or ref
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          allow-unsafe-pr-checkout: true # required to checkout PR code from forks, PRs from external people need to be approved anyways
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install CubitPy
        run: |
          whoami
          pwd
          # Install dependencies
          sudo apt update
          sudo apt install libhdf5-dev libnetcdf-dev build-essential

          # Install cubitpy
          pip install --upgrade pip
          pip install -e .[dev]
          # Print information on the python environment
          python --version
          pip list
      - name: Setup local SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

          mkdir -p ~/.ssh
          ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519
          cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          sudo service ssh start
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts
      - name: Verify SSH connection
        run: ssh localhost 'echo SSH to local host successful'
      - name: Setup Coreform
        id: cubit
        uses: beamme-py/beamme/.github/actions/cubit_setup@main
        with:
          cubit_download_url: ${{ env.CUBIT_DOWNLOAD_URL }}
          cubit_email: ${{ secrets.CUBIT_EMAIL }}
          cubit_password: ${{ secrets.CUBIT_PASSWORD }}
      - name: Run CubitPy tests in local mode
        run: |
          # Create CubitPy config
          CONFIG_NAME=cubitpy_config_local.yml
          cat > $CONFIG_NAME <<EOF
          cubitpy_mode: "local"
          local_config:
            cubit_path: "$CUBIT_ROOT_PATH"
          EOF
          cat $CONFIG_NAME
          export CUBITPY_CONFIG_PATH="$(pwd)/$CONFIG_NAME"

          # Run tests
          pytest
          # This tests that if cubit is completely closed everything works
          cd tests
          ./test_configurations.sh
        env:
          CUBIT_ROOT_PATH: ${{ steps.cubit.outputs.cubit_root }}
      - name: Run CubitPy tests in remote mode
        run: |
          # Create CubitPy config
          SSH_USER="${USER:-$(whoami)}"
          CONFIG_NAME=cubitpy_config_remote.yml
          cat > $CONFIG_NAME <<EOF
          cubitpy_mode: "remote"
          remote_config:
            user: "$SSH_USER"
            host: "localhost"
            platform: "linux"
            cubit_path: "$CUBIT_ROOT_PATH"
          EOF
          cat $CONFIG_NAME
          export CUBITPY_CONFIG_PATH="$(pwd)/$CONFIG_NAME"

          # Run tests
          pytest
          # This tests that if cubit is completely closed everything works
          cd tests
          ./test_configurations.sh
        env:
          CUBIT_ROOT_PATH: ${{ steps.cubit.outputs.cubit_root }}
      - name: Free cubit license
        if: ${{ always() }}
        uses: beamme-py/beamme/.github/actions/cubit_finalize@main
        with:
          cubit-root: ${{ steps.cubit.outputs.cubit_root }}
